### ISSUE TITLE
(feature request) Improve tooltip display

### ISSUE THREAD

**Issue by ncave** [fable-compiler/repl2#13]
Bring some of that [awesomeness](https://github.com/ionide/ionide-vscode-fsharp/pull/861) here.

**Comment by MangelMaxime** [comment]
Here you go :)

![2018-08-04 21 13 01](https://user-images.githubusercontent.com/4760796/43679761-5a497e30-982b-11e8-8001-05c223899178.gif)

I fixed some color problem due to the black theme :) I think we will have some small problem over time until we fix them all, but the nice looks is worth it IMO :)

And also, I made `monaco-editor-hover-content` class follow the same rules as `content` class from bulma. This help ensure having nice spacing around the paragraph, nice typography etc.
