### ISSUE TITLE
include Feliz package

### ISSUE THREAD

**Issue by JaggerJo** [fable-compiler/repl2#3]
would be super nice to play around / share small demos if Feliz was packaged with the repl

**Comment by MangelMaxime** [comment]
Hello, 

we can't add support for Feliz package in Fable 2 repl because Feliz is using `inline` everywhere and Fable 2 repl pre-compile the libraries meaning that inlined function are not supported.

Fable 3 repl doesn't support yet libraries but I think @alfonsogarciacaro said he had some ideas on how to make them work with less limitation and also in an easier way to include.

I am closing this issue as there is nothing we can do about it in Fable 2 repl. Sorry
