### ISSUE TITLE
(feature request) Code/Live vertical separation

### ISSUE THREAD

**Issue by ncave** [fable-compiler/repl2#4]
Would it be better if the Live sample and the generated code be vertically separated, with title bars to shrink/expand them, same way as on the left? Essentially, a four-window scheme, as every other JS playground. I understand that the current design saves one title bar to get more space on the right, so there are pros and cons, what do you think?

**Comment by MangelMaxime** [comment]
Originally, I was planning to add the console output in the bottom right section. I am speaking about the console coming from the iframe.

**Comment by alfonsogarciacaro** [comment]
As long as editors can be collapsed, I wouldn't mind to have this layout. [I did find some glitches because of the hidden editor](https://github.com/fable-compiler/repl2/blob/0ab466d16925c802feb58d1628ff01bc70dafc5e/src/App/Generator.fs#L40-L43). If we implement this, I guess we should also add a mechanism to edit and reload the JS code without recompiling F#.

The console output is tricky, in Chrome everything goes to the same console, so I can see there logs from worker, main app and iframe. But apparently it's not the case in other browsers. I'm not sure how the console output from the iframe can be redirected. In one of the first REPL versions I had some trickery for that, but it involved replacing `printfn` calls.

Anyways, now that we have Elmish & React in the repl, it should be also easy to include by default a component that can show logs in the web page.

**Comment by MangelMaxime** [comment]
> I guess we should also add a mechanism to edit and reload the JS code without recompiling F#.

Not sure to understand this part, the JS code shouldn't be edited by the user and I made it readonly for this reason.

> The console output is tricky, in Chrome everything goes to the same console

Same for every Firefox, but the trick is to listen to provide a custom console implementation in the iframe and use it to catch the logs and send them back to the main window via an event.

**Comment by ncave** [comment]
IMO the javascript should be read-only, as it's generated. I'm not sure what is the value of showing console output, that's what F12 is for. Perhaps the compilation logs can go to the generated code window if there are errors during the conmpilation.

**Comment by MangelMaxime** [comment]
My problem with using the F12, is that it take a lot of place :) Where adding

**Comment by MangelMaxime** [comment]
Re-adding the ability to modify the JavaScript is easy: https://github.com/fable-compiler/repl2/blob/master/src/App/Main.fs#L448

I am in favor of read-only mode but open to suggestion because in general, I rarely explore the generated JavaScript :)

**Comment by MangelMaxime** [comment]
In the last couples of days, I thought a lot about this issue. And I can see 3 separated use case for the REPL:

1. The user wants to play with the REPL and do some visualization stuff. 
    - Mainly interested in the **Live sample** tab
    - Can sometimes be interested in the **Console** output for debug purpose. Like printing variables values
2. The user wants to check the generated code. 
   - Only interested in the **Code** tab
3. The user wants to test some code, see if Fable supports it, etc.
   - Mainly interested in the **Console**

So I propose for now to provide 3 tabs on the right panel:
- Live sample
- Code
- Console

Or to have a split layout on the right panel:
- Top part
   - Live sample
   - Code
- Bottom part
   - Console

The bottom part can be expanded/collapse in order to maximize the available space.

What do you think?

**Comment by alfonsogarciacaro** [comment]
Displaying the console below the Live Sample/Code probably would be very helpful for users. How are you planning to do it? By overwriting the `console` value?

**Comment by forki** [comment]
Do you even need a compile button?

Alfonso Garcia-Caro <notifications@github.com> schrieb am Sa., 22. Sep.
2018, 13:23:

**Comment by alfonsogarciacaro** [comment]
Well, I think so, because new users may not know the key shortcut and some people may even prefer it. If you're talking about automatic compilations every X seconds, for now I'll avoid that because the big samples getting close to 1000 lines can take some seconds to compile.

**Comment by MangelMaxime** [comment]
> How are you planning to do it? By overwriting the console value?

I will wrap the console function to capture their call to send them back into our Application and then trigger the native implementation. I made a quick POC this morning and it seems to be working.

> Do you even need a compile button?

We do need the compile button because compilation is slow, so we need this action to be triggered by the user.

**Hello world sample**
<img width="291" alt="capture d ecran 2018-09-22 a 14 08 28" src="https://user-images.githubusercontent.com/4760796/45917130-28ce7100-be71-11e8-9325-47a61dc20412.png">

**Color fountain sample**
<img width="294" alt="capture d ecran 2018-09-22 a 14 09 10" src="https://user-images.githubusercontent.com/4760796/45917131-2b30cb00-be71-11e8-9ac2-ee5093c40edc.png">

The navbar don't take that much place but I will see if I can place the button somewhere else. Because I also want to add a `Reload button` who just reload the `Live sample` this is usefull when you want to check runtime performance or have some random in your simulation like generating a random image etc.

**Comment by alfonsogarciacaro** [comment]
22 secs to compile the fountain sample! 😮 Wow, Firefox is really slow! That sample can compile in less than one sec in my machine if it has no pressure from other apps. Also in m machine, Firefox compiles it in 8s (without pressure).

**Comment by MangelMaxime** [comment]
Indeed Firefox is very slow. I compiled the same template on the same machine with Chrome:

**Hello world sample**
<img width="297" alt="capture d ecran 2018-09-22 a 15 14 50" src="https://user-images.githubusercontent.com/4760796/45917566-50760700-be7a-11e8-97fc-ae81a9269d55.png">

**Color foutain sample**
<img width="290" alt="capture d ecran 2018-09-22 a 15 15 00" src="https://user-images.githubusercontent.com/4760796/45917568-523fca80-be7a-11e8-81a3-f0b1f7c9d429.png">

Last time I checked the difference wasn't that hight but I should definitely work on REPL with Chrome and Firefox (less loading screen^^).

**Comment by ncave** [comment]
+1 for moving the compile button to the top of the toolbar on the left, would free a lot of vertical space at the top.

**Comment by MangelMaxime** [comment]
Indeed we gain some space but it can be hard to understand that they are button and not menu.

Will try different layouts and see/share the results.

**Comment by ncave** [comment]
> but it can be hard to understand that they are button and not menu.

The collapse button on the same toolbar (at the bottom) for example is a button and not a menu, so perhaps something similar can work.

**Comment by MangelMaxime** [comment]
I don’t think this is the same case. 

When the sidebar is collapse this button is separated from the rest. And when extended it have the same design has the widgets headers with a text to inform that there is an action. 

Even like that this is not always clear that you can click on it. The visual feedbacks are really smalls. 

We need to make sure that the compile & reload button are easily identifiable as button. 

I just got an idea of using an outlined colored button so visually they are différents from the rest. Will try it

**Comment by MangelMaxime** [comment]
Ok, I think using a different style is promising.

![2018-09-24 10 34 14](https://user-images.githubusercontent.com/4760796/45943138-6e13af80-bfe5-11e8-92e9-f25fbe9f5b9d.gif)

*Need to fix the placement*

**Comment by MangelMaxime** [comment]
Here is my new proposition.

![2018-09-24 14 26 17](https://user-images.githubusercontent.com/4760796/45952002-e25e4b00-c005-11e8-8749-52d33402a193.gif)

**Comment by ncave** [comment]
@MangelMaxime It's awesome, so good!
Are the reset and refresh different somehow? Can they be merged into just a single reset button (without confirmation, IMO there's not need for that)?

**Comment by MangelMaxime** [comment]
@ncave They are indeed different.

- Refresh
    - only re-run the iframe with latest `jsCode` received.
- Reset
    - reset the Html code and F# as if the REPL has just been loaded.

I need to add some tooltip to explain some of the action and probably rename the refresh button to `Re-run` or something like that.

**Comment by ncave** [comment]
@MangelMaxime Not the refresh, refresh makes sense, I was referring to the "Refresh Samples" below, which seems unnecessary now, together with the "SAMPLES" title below it.

**Comment by MangelMaxime** [comment]
@ncave Ah no, you can ignore this button. This is something only displayed in dev mode in order to reload the samples information without reloading the whole tab. Allow us to have a quick feedback.

**Comment by ncave** [comment]
Other possible layouts here: https://webassembly.studio/
Treeview on the left, merged problems/error panes at the bottom.
